### ISSUE TITLE
i am struggling in installation for two days please help me final paragraph of installation needs help

### ISSUE THREAD

**Issue by mecccu** [OpenCVBlueprints/OpenCVBlueprints#14]
hello 
I cannot understand the last part of the installation guide.
I opened gedit and pasted the test code with the image path replaced with "/media/koj/Ubuntu-Server 16.04.1 LTS amd64"
and I activated external tools at gedit so there appeared "build" at the "external tools"
so when i pressed build at the gedt 
Running tool: Build

No Makefile found!

Done
can you explain why this happen? and what does it mean in the below which says "configure your editor to include the build and opencv repositories"

![ubuntu 64-bit 3 -2016-08-29-16-41-21](https://cloud.githubusercontent.com/assets/21294401/18044181/75bff0b8-6e07-11e6-9b00-3919474227af.png)

Make sure that you replace the image path with an actual image path that exists! Then, configure your editor to include the build and installed OpenCV repositories. Under Ubuntu, you can do that by pointing your linker to

`pkg-config opencv --libs`
which will auto grab all the dependencies. This can be done inside your IDE on the linker settings tab or by executing the following command

$ g++ test.cpp -o test `pkg-config opencv --libs`
using the command line. Since all headers are installed into /usr/local/lib/, you do not need to explicitly tell that to the system, since Ubuntu can handle that itself.

**Comment by mecccu** [comment]
![ubuntu 64-bit 3 -2016-08-29-16-49-59](https://cloud.githubusercontent.com/assets/21294401/18044414/b327fc88-6e08-11e6-9479-d3733e20aa51.png)

**Comment by StevenPuttemans** [comment]
@mecccu welcome back, let me see how I can help you

> I opened gedit and pasted the test code with the image path replaced with "/media/koj/Ubuntu-Server 16.04.1 LTS amd64"

You need to make sure that the path is pointing to an actual image, taking the following rules into account
 * Ubuntu copes very bad with image paths with spaces. Change it to an image that has no spaces in its name AND provide the actual extension. For example `/media/koj/image.jpg`
 * Make sure the image is physically there

> and I activated external tools at gedit so there appeared "build" at the "external tools"
so when i pressed build at the gedit

If you want gedit as a building tool, that is very complex. By default it is just a text editor that is able to use cmake to build code if you want it... It indeed forces you to write a MakeFile which is fairly complex without experience. A tutorial on making those makefiles can be found [here](http://mrbook.org/blog/tutorials/make/).

> configure your editor to include the build and opencv repositories

This means that you need to setup a programming environment on your system. Again, these are prerequisites for the book. You must have some experience in programming in linux. If not, you will need to find a tutorial on how to setup an IDE, which is a programming interface. For example, Code::Blocks is a decent one for Ubuntu.

**Comment by StevenPuttemans** [comment]
And with the second window, can you please more your mouse so the command is visible?

**Comment by mecccu** [comment]
thanks for your reply steven
I never used linux before I just have little experience with windows IDE for c++ .
I thought gedit was IDE program.
Which IDE program do you recommend to install.
I think configure your editor to include build and opencv repositories is the most difficult for me.
Which IDE do you use and how did you configured ? 
where should I write this command $ g++ test.cpp -o test `pkg-config opencv --libs`
at the ubuntu console or at the ide environment?
I thought this book was an introductory book which I could follow.

**Comment by mecccu** [comment]
![ubuntu 64-bit 3 -2016-08-29-16-53-13](https://cloud.githubusercontent.com/assets/21294401/18044682/00a7a2b4-6e0a-11e6-8cca-7630abf5bc47.png)

**Comment by StevenPuttemans** [comment]
So again some remarks

> I never used linux before I just have little experience with windows IDE for c++ .

Then why switch to linux? Is this a requirement? You are making it more difficult for you then you have too. OpenCV just runs fine on Windows also!

> Which IDE program do you recommend to install.

As said before, try code:blocks, which can be found [here](http://www.codeblocks.org/). It is easy to setup in my opinion if you know what IDE specific compiler settings and linker settings are. But this is general over operating systems.

> Which IDE do you use and how did you configured ? 

The configuration cannot be done by us. This is different for every single system out there and the responsibility of the user. For codeblocks, you will need to go the your project build options, select the compiler tag and add that line to additional resources.

> I thought this book was an introductory book which I could follow.

The official dealer of the book, Packt Publishing, clearly states on the [books website](https://www.packtpub.com/application-development/opencv-3-blueprints) that the intended audience for Blueprints type of books is

> Guides you through the most common types of project you'll encounter, giving you end-to-end guidance on how to build your specific solution quickly and reliably. 

This is not a beginners level... For that you need a whole other range of books ...

> As to the error in your image. As @JoeHowse already said before. You skipped the part of installing the OpenCV dependencies and thus the `g++` compiler is not installed on your system. For that run the command `sudo apt-get install build-essential`. But I urge you to go back to the beginning of the tutorial and install all those dependencies mentioned there.

**Comment by mecccu** [comment]
Thanks for kind explanation.
I already installed build essentials from the beginning.
![ubuntu 64-bit 3 -2016-08-29-17-24-05](https://cloud.githubusercontent.com/assets/21294401/18045371/88cde402-6e0d-11e6-998f-8f457c2d93ed.png)

I think there should be more details of setting the IDE environments in the book.
Which may be tricky for everyone in my opinion.I think that part is very difficult to remember for the author himself so he omitted.
I will try code block as ide environment.

I changed to linux becuse the book had little explanation at the windows environment.

Maybe a bad choice for this book.
I think I have to buy another book for introduction of ide setting.
I live in korea so I cannot see all the book.just amazon preview and bought this book.
Any way thanks for your kind reply.
Bye
![ubuntu 64-bit 3 -2016-08-29-17-24-05](https://cloud.githubusercontent.com/assets/21294401/18045505/186f8598-6e0e-11e6-89d5-b1bc6b0dc73f.png)

**Comment by StevenPuttemans** [comment]
> I think there should be more details of setting the IDE environments in the book.

No there should not, because these series consider that a reader is perfectly able to setup OpenCV, program and compile C++ code and get his Linux system configured correctly. It is possible to write a whole book purely focussing on that...

> I think that part is very difficult to remember for the author himself so he omitted.

I guess you are not really understanding that me and @JoeHowse are in fact authors of this book and we did not omit anything. If you have the knowledge prerequisites for this type of book, then the instructions left are more then enough. We simply did not write a book that is for OpenCV starters ... they are not the intended public.

> I changed to linux becuse the book had little explanation at the windows environment.

The book uses about 4 different system setups, which is the concept of the book. However, if you have a background in programming, transfering the code from one system to another should be straightforward.

> buy another book for introduction of ide setting

I do not think that there are many books on that. A suggestion: http://www.dummies.com/programming/c/basics-of-codeblocks-ide-for-c-programming/

> I live in korea so I cannot see all the book

Too bad -_- still don't get these censorships ...

**Comment by mecccu** [comment]
Thanks I think code block for ubuntu is very hard to install.
I do not understand ppa and its frustrating me and I have to go back to windows for sure.
I think there is a big gap between professionally trained computer programmer and a newcommer from different discipline.
for me the installing and setup part is most time consuming and hard.the algorithm is not a problem.
Have a nice day.
I will check google how to install code block .

**Comment by StevenPuttemans** [comment]
Codeblocks is available in software center and has been for ages, a simple `sudo apt-get install codeblocks` will install it for you. Not that difficult right?

> I think there is a big gap between professionally trained computer programmer and a newcommer from different discipline.

Of course there is. That is why there are books like the `for dummies` collections, that explain every basic detail step by step. 

> for me the installing and setup part is most time consuming and hard.the algorithm is not a problem.

I am really afraid you are wrong here. If setting up a `hello world` example is that difficult for you, be prepared to hit some major brick walls while programming...

**Comment by mecccu** [comment]
I learned ide on windows with book written by Bjarne Stroustrup 's programming principles and practice using c++.
As you wrote hello world is the most big step for everyone.
And that book guide me to hello world.It was not easy at first to configure that ide.
I wish when steven and joe have enough time write something about that install process more clearly.
Not generally but what you use it is enough.
you can find so many questions and answers about installing all kinds of program in google.
That shows how many people struggle for installing.
I found code block on sofftware center and installed it.
Thank you very much.
I will try to configure it relying on my C++ knowledge about linking and header and so on.
Thanks a lot.

**Comment by StevenPuttemans** [comment]
> I wish when steven and joe have enough time write something about that install process more clearly.

Again, that is not the aim of this book. The book is for a advanced user of computer vision, who already grasps the basics or is looking for something very specific. It will not give you the basics around OpenCV programming in Linux.

> you can find so many questions and answers about installing all kinds of program in google.

True, but you can find an equal amount of decent tutorials out there explaining it all step by step. Most of the times new issues arise because people are too lazy to actually look for a solution before calling others help.
