### ISSUE TITLE
why code block does not detect g++ install in ubuntu

### ISSUE THREAD

**Issue by mecccu** [OpenCVBlueprints/OpenCVBlueprints#16]
![ubuntu 64-bit 3 -2016-08-30-00-42-13](https://cloud.githubusercontent.com/assets/21294401/18057414/db3085d2-6e4a-11e6-9d76-4bb071e1ae1d.png)
![ubuntu 64-bit 3 -2016-08-30-00-43-25](https://cloud.githubusercontent.com/assets/21294401/18057421/df43dbe2-6e4a-11e6-83f3-9fd2b9698d50.png)
I installed g++ and when i go into the code block and open a console application project.
ANd I seleted C++ as my language and then the next page shows gnu GCC compiler and all the other things except g++.
I heard that I should have g++ compiler to follow this book but why the code block does not detect installed g++?
I searched google for hours but everybody just says about installing build essential which i already did two days ago.
Still struggling for installation
give me some help.

**Comment by JoeHowse** [comment]
GCC will use g++ for files with the .cpp extension, so the "GNU GCC Compiler" setting should be okay.

In future, for general questions about Linux, IDEs, C++, etc., please use a general-purpose support forum such as StackOverflow, and please consult beginner's books on these topics.

Also, please note that our installation guide and book do contain instructions about compiling the book's C++ projects on the Linux command line.  Of course, you may choose to use an IDE instead, but we are not available to teach you how to use your chosen IDE.  As Steven has previously discussed with you, _OpenCV 3 Blueprints_ is an advanced book on OpenCV, the typical reader for this level of book has diverse and extensive programming experience, and you need to look elsewhere for beginner's-level support on other topics such as Linux usage.  You will gain much more from this book if you first take the time to study general-purpose programming guides for your chosen platform (Linux).
