### ISSUE TITLE
Building opencv 3 and tesseract ocr.

### ISSUE THREAD

**Issue by Tegdam** [OpenCVBlueprints/OpenCVBlueprints#2]
Following the instructions, I 

1. created a directory in "C:\" called "CVmodules" where I put the zips downloaded from the Itseez link(opencv-master and opencv_contrib-master).

2. In the Cmake GUI selected the opencv source code folder (C:\CVmodules\opencv) and the folder where binaries will be built (C:\CVmodules\contribBuild)

3. pressed the configure button.

4. browsed the parameters in the interface and look for the form called OPENCV_EXTRA_MODULES_PATH 

5. completed this OPENCV_EXTRA_MODULES_PATH by the proper pathname to the <opencv_contrib>/modules value (C:\CVmodules\opencv_contrib\modules).

6. then pressed the configure button 

However, the picture below is all I see when research tessearct. There is no way to enable tesseract.
I also realized that there seem not to be a tesseract library, in the tesseract that I installed,to point it to. I downloaded it from 
https://code.google.com/p/tesseract-ocr/downloads/detail?name=tesseract-ocr-setup-3.02.02.exe&can=2&q=

What am I doing wrong? Did download the wrong version of the tesseract. This is for visual studio 2013 in windows 8. I already have opencv 3 installed using the prebuilt libraries method. Should uninstall and build it instead?

![image](https://cloud.githubusercontent.com/assets/12734496/12386690/5cf848e6-bd95-11e5-85c3-06c6beb3d7a4.png)

**Comment by StevenPuttemans** [comment]
@Tegdam I am sorry but this is a repository related to the code which is associated with OpenCV 3 Blueprints, a recently released Pact Publishing book. We want to keep the issues to book or source code related issues. 

For general OpenCV related issues, I suggest you to go to http://answers.opencv.org/questions/ and address your problem there to get help in the fastest way possible.

Therefore I would close this for now. However if you disagree, please respond and let me know!

**Comment by Tegdam** [comment]
I understand. I will re-post it on the opencv website.

**Comment by StevenPuttemans** [comment]
Thank you in advance!
