### ISSUE TITLE
Some packages are not found in Linux Installation

### ISSUE THREAD

**Issue by sato-cloudian** [OpenCVBlueprints/OpenCVBlueprints#3]
Hi, thanks for those detailed instructions.

My env is Ubuntu 14.04.3.

```
apt-get install build-essentials
```
This is supposed to be:

```
apt-get install build-essential
```

And this is:

```
apt-get install cmake cmake-qt-gui git pkg-config libgtk2.0-dev libavcodec-dev libformat-dev libswscale-dev
```
supposed to be:

```
apt-get install cmake cmake-qt-gui git pkg-config libgtk2.0-dev libavcodec-dev libavformat-dev libswscale-dev
```

One more. libeigan-dev not found.

```
apt-get install libeigen-dev libeigen2-dev libeigen3-dev
```
No alternative I came up with.

```
apt-get install libeigen2-dev libeigen3-dev
```

Also, I suggest to add sudo for Ubuntu installation commands.

**Comment by JoeHowse** [comment]
Thanks! I have revised the tutorial as suggested.

**Comment by StevenPuttemans** [comment]
Thank you for the report. I would love to suggest to replace

`apt-get install libeigen2-dev libeigen3-dev`

by

`apt-get install libeigen-dev`

because it will ensure that always the most stable version for the OS is being installed.  @JoeHowse shall I update it?

**Comment by JoeHowse** [comment]
http://packages.ubuntu.com does not list libeigen-dev, and I believe the OP is reporting that this package is not found on Ubuntu 14.04.3. On which OS version does it work for you @StevenPuttemans?

**Comment by StevenPuttemans** [comment]
Ow you are correct. Well I have the same Ubuntu so both might work. Then the fix is indeed good as it is :)
