### ISSUE TITLE
Required OpenCV version for fingerprint_process.cpp

### ISSUE THREAD

**Issue by mike-wsu** [OpenCVBlueprints/OpenCVBlueprints#31]
Hello,

I am trying to get the fingerprint functionality up and running (OpenCVBlueprints/chapter_6/source_code/fingerprint/fingerprint_process/fingerprint_process.cpp). The file shows OpenCV2 is required.

I tried using OpenCV 2.4, however it did not work with the fingerprint algorithm. Could someone point me to the correct OpenCV version i should use?

Thanks,
Mike

**Comment by JoeHowse** [comment]
Hi Mike,

Like the rest of the book, fingerprint_process.cpp uses OpenCV 3.

Code such as the following does _not_ imply a dependency on OpenCV 2:

`#include "opencv2/opencv.hpp"`

Rather, in this context, "opencv2" refers to the C++ headers rather than the older "opencv" C headers.
