### ISSUE TITLE
Chapter 5 Mat rotated isn't correctly defined before usage 

### ISSUE THREAD

**Issue by DylanVanAssche** [OpenCVBlueprints/OpenCVBlueprints#32]
# What's happening
Preprocessing happens on undefined Mat objects. It will not make a difference on the output result.

# What should be happening
Preprocessing should be happening in the for loop to be effective.

# Environment

- Arch Linux x64
- CLion 2018.6
- OpenCV 3.4.3

# Link
https://github.com/OpenCVBlueprints/OpenCVBlueprints/blob/master/chapter_5/source_code/rotation_invariant_detection/rotation_invariant_object_detection.cpp#L82-L95

**Comment by quanhua92** [comment]
Thank you very much. I've merged our PR.
