### ISSUE TITLE
building test.cpp

### ISSUE THREAD

**Issue by sato-cloudian** [OpenCVBlueprints/OpenCVBlueprints#4]
Hi,

>  Under Ubuntu, you can do that by pointing your linker to
> ```
> pkg-config opencv --libs
> ```
> which will auto grab all the dependencies. 

Is this what you meant?

```
$ g++ test.cpp -o test `pkg-config opencv --libs`
```

Then, writing so is more helpful, though it might be obvious.

**Comment by StevenPuttemans** [comment]
Added the suggestion: https://github.com/OpenCVBlueprints/OpenCVBlueprints/commit/64ff5543afe325dc56ec9698e74bdd32963f814a 

Still a small problem is that Github does not display the single quotes when using the preformat tag ... Will look into a solution for this.

**Comment by StevenPuttemans** [comment]
Fixed it!

**Comment by liuhengli** [comment]
error329	error LNK1104: could not open file“..\..\lib\Debug\opencv_bioinspired310d.lib”	E:\opencv\src\build\vs2012x64\modules\bioinspired\LINK	opencv_test_bioinspired.
what'swrong???

**Comment by liuhengli** [comment]
build OpenCV.sln have some errors
错误	133	error MSB6006: “cmd.exe” -1073741571。	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets	172	5	opencv_bioinspired
错误	406	error LNK1181: can not open input file“..\..\lib\Release\opencv_bioinspired310.lib”	E:\OpenCV\build\vs2012x64\modules\bioinspired\LINK	opencv_perf_bioinspired
what I need do???
