### ISSUE TITLE
./object_annotation does not write to the file specified

### ISSUE THREAD

**Issue by JohnAllen** [OpenCVBlueprints/OpenCVBlueprints#7]
I tried using sudo too.  The program works, but it does not write to the annotations file.  I noticed in another issue that this program should no longer be used.  Would be great if the updatable book said that!  

If someone knows how to get it working, please let me know.  I see there's an OpenCV provided tool, but haven't found the params for that yet.

**Comment by StevenPuttemans** [comment]
Actually did you check the latest commit on that code? https://github.com/OpenCVBlueprints/OpenCVBlueprints/commit/816a9a76593b42bdb4671a81309f8927440be6f6

I forgot a break statement indead leading to no output being written.µ

As to the opencv tool, just hit opencv_createsamples in command line in Linux if you installed the apps and the required parameters you need to pass will pop up.

**Comment by JohnAllen** [comment]
I cloned

https://github.com/OpenCVBlueprints/OpenCVBlueprints.git

on Friday.  I assume it had all commits to that point.  That is the main .git link on the main repo page.  I will check and see if it didn't have the `break;` statement you mentioned.

**Comment by JohnAllen** [comment]
It appears that what I cloned does have that `break` statement.  

A work-around I developed, which is not a great one at all, is to split up the files into separate sub-directories, and open the annotation tool in each of those directories.  When the files in each sub-directory have each been annotated, I write their annotations to a local annotations file, then copy the contents up to a main one.  The gist of the solution is using the annotations tool in a smaller directory.  It will write the annotations to a file once the directory runs out of images to annotate.

**Comment by StevenPuttemans** [comment]
I will have a look why it is not working. As to the notice of not using it, that is actually not completely true, because the code should essentially be similar and I know that the integrated tool is fully working (used it 30 minutes ago to confirm).

I will take a look at the code provided here and keep you posted about what works and what does not.

**Comment by StevenPuttemans** [comment]
Hello @JohnAllen, like being said, there was indeed some code mistakes in the annotation app here. I have updated and tested it on my local system and the [following commit](https://github.com/OpenCVBlueprints/OpenCVBlueprints/commit/a8d469c3c8df12af0dcefe148d2c888695a41ec2) should solve the issues.

Please re-open if the problems still remain.

BTW also added a notice on the newer opencv - integrated tool!

**Comment by StevenPuttemans** [comment]
Just to let you know, I have updated the OpenCV annotation tool with the following options
* Early quitting and storage option
* A delete option to delete missclicked annotations

Take a look here: https://github.com/Itseez/opencv/pull/6382
